# Generated by Django 4.1 on 2022-11-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_author_user_is_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_special',
            new_name='special_user',
        ),
    ]
